version: "3.7"
services:
  app:
    build:
      args:
        user: admin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: backend
    container_name: backend-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - nginx
      - phpmyadmin
    networks:
      - backend
      
  db:
    image: mysql:5.7
    container_name: backend-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: nurul-imam-db
      MYSQL_PASSWORD: strongrootpassword
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: strongrootpassword
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    networks:
      - backend
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: backend-nginx
    restart: unless-stopped
    ports:
      - 8004:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    container_name: backend-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      # PMA_USER: root
      # PMA_PASSWORD: strongrootpassword
    ports:
      - "8083:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
